# """
# Filename: test_project.py
# Author: Auto-generated by Copilot, reviewed by Abbas Jabor
# Date: November 30, 2025

# Unit tests for project-related stored procedures.
# Ensures insert/select/delete flows for projects work as expected.

# To run - pytest
# """

# import pytest
# from app import app, mysql

# # Application context fixture
# @pytest.fixture
# def app_context():
#     with app.app_context():
#         yield

# # DB cursor fixture
# @pytest.fixture
# def db_cursor(app_context):
#     cursor = mysql.connection.cursor()
#     yield cursor
#     cursor.close()

# # Sample data fixtures
# @pytest.fixture
# def sample_institution():
#     return {
#         "institution_name": 'test institution',
#         "institution_type": "Test",
#         "street": "99 Remove Rd",
#         "city": "Removeville",
#         "state": "RV",
#         "zipcode": "54321",
#         "institution_phone": "555-5432",
#     }

# @pytest.fixture
# def sample_department():
#     return {
#         "department_phone": '(123) 456 7890',
#         "department_email": "test@test.com",
#         "department_name": "test dept",
#     }

# @pytest.fixture
# def sample_person():
#     return {
#         "person_name": 'Mr. Test',
#         "person_email": "test@test.com",
#         "person_phone": "(123) 456 7890",
#         "bio": 'test bio',
#         "expertise_1": "test expertise_1",
#         "expertise_2": "test expertise_2",
#         "expertise_3": 'test expertise_3',
#         "main_field": "test field",
#     }

# @pytest.fixture
# def sample_project():
#     return {
#         "title": "Test Project",
#         "description": "A test project for unit tests",
#         "start_date": "2025-01-01",
#         "end_date": "2025-12-31",
#         "tag_name": "unit-test",
#     }

# # Helper to call procedures consistently

# def call_procedure(cursor, proc_name, params):
#     cursor.callproc(proc_name, params)
#     try:
#         result = cursor.fetchone()
#     except:
#         result = None
#     while cursor.nextset():
#         pass
#     return result


# def test_insert_select_delete_project(db_cursor, sample_institution, sample_department, sample_person, sample_project):
#     """End-to-end test for InsertIntoProject, SelectProjectById, and DeleteProject."""
#     # Insert Institution
#     result_institution = call_procedure(
#         db_cursor,
#         "InsertIntoInstitution",
#         [
#             sample_institution["institution_name"],
#             sample_institution["institution_type"],
#             sample_institution["street"],
#             sample_institution["city"],
#             sample_institution["state"],
#             sample_institution["zipcode"],
#             sample_institution["institution_phone"],
#         ],
#     )
#     mysql.connection.commit()
#     institution_id = result_institution["new_id"] if result_institution else None
#     assert institution_id is not None

#     # Insert Department
#     result_department = call_procedure(
#         db_cursor,
#         "InsertIntoDepartment",
#         [
#             sample_department["department_phone"],
#             sample_department["department_email"],
#             sample_department["department_name"],
#             institution_id,
#         ],
#     )
#     mysql.connection.commit()
#     department_id = result_department["new_id"] if result_department else None
#     assert department_id is not None

#     # Insert Person
#     result_person = call_procedure(
#         db_cursor,
#         "InsertPerson",
#         [
#             sample_person["person_name"],
#             sample_person["person_email"],
#             sample_person["person_phone"],
#             sample_person["bio"],
#             sample_person["expertise_1"],
#             sample_person["expertise_2"],
#             sample_person["expertise_3"],
#             sample_person["main_field"],
#             department_id,
#         ],
#     )
#     mysql.connection.commit()
#     person_id = result_person["person_id"] if result_person else None
#     assert person_id is not None

#     # Insert Project (requires person_id)
#     result_project_insert = call_procedure(
#         db_cursor,
#         "InsertIntoProject",
#         [
#             sample_project["title"],
#             sample_project["description"],
#             person_id,
#             sample_project["start_date"],
#             sample_project["end_date"],
#             sample_project["tag_name"],
#         ],
#     )
#     mysql.connection.commit()
#     project_id = result_project_insert["new_id"] if result_project_insert and "new_id" in result_project_insert else None
#     # Some procedures may not return new_id; fallback: select by person
#     if project_id is None:
#         # Try to fetch last inserted project for person
#         result_projects = call_procedure(db_cursor, "SelectProjectsByPersonID", [person_id])
#         # Depending on procedure, this might return one row or None
#         if result_projects and "project_id" in result_projects:
#             project_id = result_projects["project_id"]
#     assert project_id is not None

#     # Select by ID
#     result_project = call_procedure(db_cursor, "SelectProjectById", [project_id])
#     assert result_project is not None
#     assert result_project.get("title") == sample_project["title"]
#     assert result_project.get("description") == sample_project["description"]

#     # Delete project
#     call_procedure(db_cursor, "DeleteProject", [project_id])
#     mysql.connection.commit()

#     # Verify deletion
#     verify_deleted = call_procedure(db_cursor, "SelectProjectById", [project_id])
#     assert verify_deleted is None

#     # Cleanup remaining entities
#     call_procedure(db_cursor, "DeletePerson", [person_id])
#     call_procedure(db_cursor, "DeleteDepartment", [department_id])
#     call_procedure(db_cursor, "DeleteInstitution", [sample_institution["institution_name"]])
#     mysql.connection.commit()
